### ISSUE TITLE
Create edit.html.

### ISSUE THREAD

**Issue by garimasingh128** [garimasingh128/profext#11]
- A form design which takes values from users for names and social media links.
- A save button at the bottom with href to popup.html
- The design should be as similar to popup.html as possible.

**Comment by navu9999** [comment]
Can i work on this issue?

**Comment by ankita841** [comment]
Please assign this to me.

**Comment by garimasingh128** [comment]
@maze-runnar has already created a PR for it. I'll review that. Till then, you can create new issues yourselves.
