### ISSUE TITLE
Adding more social media icons and corrections.

### ISSUE THREAD

**Issue by garimasingh128** [garimasingh128/profext#18]
1. Add social media icons for the following:
- Blog website
- Medium
- Bitbucket
2. Correct the color pallette of existing and new icons. For example: For Github use black and white icon instead of the already present green one.

**Comment by anmolkaur18** [comment]
I am interested 😊 Assign it to me please

**Comment by Abjcodes** [comment]
Hey @garimasingh128, I would like to work on this issue.

**Comment by dijodaiju7** [comment]
Hey @garimasingh128, I would like to work on this issue. Can you please assign it to me.

**Comment by Abjcodes** [comment]
Hey @garimasingh128, since there are multiple assignees, how should we work on this issue?

**Comment by garimasingh128** [comment]
For design issues, there will be multiple assigned and every one's PR will be taken into consideration.
For code issues, there can also be multiple assigned and the one who does the part  with most accurate implementation will have his/her PR merged and the other's PRs won't be counted.
This one is a code issue.

**Comment by snehaM2210** [comment]
I want to work on this issue. Please assign it to me @garimasingh128 .

**Comment by Ayushgup85** [comment]
is this issue still open?

**Comment by garimasingh128** [comment]
no
