### ISSUE TITLE
{Question} About the functionality

### ISSUE THREAD

**Issue by Suleman-Elahi** [garimasingh128/profext#24]
How it is different than simple bookmarking? That is also one-click access to social media accounts.

**Comment by garimasingh128** [comment]
This was my first attempt to create a chrome extension. I think it is a personalised form of bookmarks only with a better UI. Moreover, The bookmarks clutter your workspace. I've been using it now since 2 months and there's no turning back!

**Comment by Suleman-Elahi** [comment]
Okay thanks...just wanted to know a usecase so I ould write about it on my blog (ilovefreesoftware.com).
