### ISSUE TITLE
Make the layout of popup.html as the design

### ISSUE THREAD

**Issue by garimasingh128** [garimasingh128/profext#38]
**Is your feature request related to a problem? Please describe.**
Make the layout of popup.html as the design.

**Describe the solution you'd like**
The design folder is present in the root of the master branch. It has all the assets and inspirational designs.

**Describe alternatives you've considered**
You can add your own insights but don't modify it considerably.

**Additional context**
No

**Comment by giteshk11** [comment]
hi @garimasingh128 , I would like to work on this issue.

**Comment by navu9999** [comment]
Can I work on this?

**Comment by ankita841** [comment]
Please assign this to me.

**Comment by garimasingh128** [comment]
> hi @garimasingh128 , I would like to work on this issue.

Go ahead. Don't forget to get the recent changes from master branch first!

**Comment by giteshk11** [comment]
Hi @garimasingh128 , please check the link below for the work i have done so far. Let me know how can i make it better.
[https://ibb.co/pbzcYKm](url)

**Comment by garimasingh128** [comment]
> Hi @garimasingh128 , please check the link below for the work i have done so far. Let me know how can i make it better.
> [https://ibb.co/pbzcYKm](url)

Can't open the link

**Comment by giteshk11** [comment]
try now [link](https://ibb.co/pbzcYKm)

**Comment by PinRathod** [comment]
I would like to work on this issue. Can I work on this?

**Comment by satcasm** [comment]
Is it still open? Can I work on this?

**Comment by garimasingh128** [comment]
It is done now. Please find another issue or create one :)
