### ISSUE TITLE
Update README.md for the following changes.

### ISSUE THREAD

**Issue by garimasingh128** [garimasingh128/profext#4]
Add the following to the README.md file:
Table of Contents
- Goal
- Current Progress
- Installation
- Usage
- System Requirements
- Learning Resources

Add some fun GIFs' wherever necessary to make it interesting.

**Comment by anmolkaur18** [comment]
I am interested. Please assign it to me

**Comment by navu9999** [comment]
Can i work on this?

**Comment by garimasingh128** [comment]
> Can i work on this?

Assigned to @navu9999
