### ISSUE TITLE
In order to ease the development workflow. It would be more convenient if we moved to Travis CI.

### ISSUE THREAD

**Issue by garimasingh128** [garimasingh128/profext#6]
Add Travis CI integration to the project.

**Comment by sanchibansal340** [comment]
Can I work on this?

**Comment by sanchibansal340** [comment]
Hi. I had a doubt, shall I integrate Travis for Docker or Node JS(JavaScript)?

**Comment by garimasingh128** [comment]
I have little experience with Docker, so Travis for nodejs would be good I think. If you have worked with docker, then you can see which one suits best.

**Comment by sanchibansal340** [comment]
Oh actually docker had been used in the project a bit so that is why I was confused. 😅

I will make it for Node.js for now

**Comment by garimasingh128** [comment]
Yeah. there was an issue that used docker so someone created a PR using it!

**Comment by sanchibansal340** [comment]
@garimasingh128 Can we close this issue?
