### ISSUE TITLE
Add pull request template

### ISSUE THREAD

**Issue by Kerveyfelix** [garimasingh128/profext#67]
Describe the solution you'd like
To ease the work of maintainer, add some checkbox in the PR request template so that a person creates pr after complying with organisations rules.

Additional context
It could look something like this:

 -Have you followed the Contribution guide?
 -Have you made corresponding changes to the documentation?
 -Your submission doesn't break any existing feature.

**Comment by Kerveyfelix** [comment]
Can you assign me this issue?

**Comment by garimasingh128** [comment]
too minor to be addresses as an issue!
