### ISSUE TITLE
Edit popup.html to be dynamic.

### ISSUE THREAD

**Issue by garimasingh128** [garimasingh128/profext#7]
Currently, popup.html has the links hardcoded. 
- Create an edit button.
- Redirect to edit.html after clicking the button.
- Remove existing hrefs in the accounts icons.

**Comment by ankita841** [comment]
Please assign this to me.

**Comment by navu9999** [comment]
Can i work on this?

**Comment by garimasingh128** [comment]
I think @maze-runnar has already created a PR for the same. I'll review that only.
